export const themes = {
  green: {
    primary: "#2e7d32",
    secondary: "#1b5e20",
    accent: "#f0b23a",
    background: "#f6f9f4",
    cardBackground: "#fff",
    textPrimary: "#1b5e20",
    textSecondary: "#556b2f",
    textDark: "#0b2e13",
    textLight: "#fff",
    iconBackground: "#f1fbf3",
    pageLabelBackground: "#f7fff8",
    arabicText: "#123e1a",
  },
  red: {
    primary: "#d32f2f",
    secondary: "#b71c1c",
    accent: "#ff9800",
    background: "#ffebee",
    cardBackground: "#fff",
    textPrimary: "#b71c1c",
    textSecondary: "#c62828",
    textDark: "#0d47a1",
    textLight: "#fff",
    iconBackground: "#ffcdd2",
    pageLabelBackground: "#ffebee",
    arabicText: "#b71c1c",
  },
  orange: {
    primary: "#f57c00",
    secondary: "#e65100",
    accent: "#ffb74d",
    background: "#fff3e0",
    cardBackground: "#fff",
    textPrimary: "#e65100",
    textSecondary: "#f57c00",
    textDark: "#bf360c",
    textLight: "#fff",
    iconBackground: "#ffe0b2",
    pageLabelBackground: "#fff3e0",
    arabicText: "#e65100",
  },
};
